[project]
name = "pdp"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64"]

[tasks]
serve = "marp slides/slides.md --html --allow-local-files -w"
compile-pdf = "marp slides/slides.md --pdf --html --allow-local-files"

[dependencies]
python = "3.12.*"
metalearners = "*"
matplotlib-base = "*"
lightgbm = "*"
pre-commit = "*"
typos = "*"
black = "*"
prettier = "*"
ruff = "*"
mypy = "*"
pre-commit-hooks = "*"
git_root = "*"
tabulate = ">=0.9.0,<0.10"
ipdb = ">=0.13.13,<0.14"
ipython = ">=8.27.0,<9"
marp-cli = ">=3.4.0,<4"
graphviz = ">=12.0.0,<13"
python-graphviz = ">=0.20.3,<0.21"
pydot = ">=3.0.1,<4"
pango = ">=1.54.0,<2"
pydotplus = ">=2.0.2,<3"
